//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_and_Asset_Management_2._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INVENTORY_MANAGEMENT_2Entities : DbContext
    {
        public INVENTORY_MANAGEMENT_2Entities()
            : base("name=INVENTORY_MANAGEMENT_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAMTUser> CAMTUsers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemOwner> ItemOwners { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
