//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_and_Asset_Management_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemOwners = new HashSet<ItemOwner>();
            this.Reports = new HashSet<Report>();
        }
    
        public int item_id { get; set; }
        public string item_brand { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public System.DateTime item_startDate { get; set; }
        public Nullable<System.DateTime> item_endDate { get; set; }
        public int item_status { get; set; }
        public string item_picture { get; set; }
        public string item_cmuNumber { get; set; }
        public string item_camtNumber { get; set; }
        public string item_serialNumber { get; set; }
        public Nullable<int> item_component { get; set; }
    
        public virtual ICollection<ItemOwner> ItemOwners { get; set; }
        public virtual ICollection<Report> Reports { get; set; }

        public override bool Equals(object obj)
        {
            if (obj is Item)
            {
                Item other = (Item)obj;
                return Equals(other.item_id, this.item_id) && Equals(other.item_brand, this.item_brand) && Equals(other.item_name, this.item_name) && Equals(other.item_description, this.item_description) && Equals(other.item_startDate, this.item_startDate) && Equals(other.item_endDate, this.item_endDate) && Equals(other.item_status, this.item_status) && Equals(other.item_picture, this.item_picture) && Equals(other.item_cmuNumber, this.item_cmuNumber) && Equals(other.item_camtNumber, this.item_camtNumber) && Equals(other.item_serialNumber, this.item_serialNumber) && Equals(other.item_component, this.item_component);
            }
            return false;
        }
    }
}
