//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_and_Asset_Management_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int report_id { get; set; }
        public int technician_id { get; set; }
        public int reporter_id { get; set; }
        public int item_id { get; set; }
        public string report_typeBroken { get; set; }
        public string report_case { get; set; }
        public string report_contact { get; set; }
        public string report_repairDetail { get; set; }
        public System.DateTime report_startDate { get; set; }
        public Nullable<System.DateTime> report_endDate { get; set; }
        public int report_statusComplete { get; set; }
        public bool report_recieveMsg { get; set; }
    
        public virtual CAMTUser CAMTUser { get; set; }
        public virtual CAMTUser CAMTUser1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
